tes:
	$(eval NETWORK_NAME=$(or $(networkName),"ethereum"))
  $(eval VAULT_TOKEN=$(or $(vaultToken),"<token_here>"))
	$(eval target_hdwallet_name=bc-wallet-$(NETWORK_NAME)-hdwallet)

	VAULT_ADDR=http://localhost:8200 \
	VAULT_TOKEN=$(VAULT_TOKEN) \
	PGPASSWORD=password \
	PGUSER=postgres \
	PGDATABASE=bc-wallet-common-trrfrm \
	PGHOST=localhost \
	PGSSLMODE=disable \
	PGPORT=5434 \
	PG_SCHEMA_NAME=bc-wallet-$(NETWORK_NAME)-hdwallet \
	terraform -chdir=deploy/trrfrm/hdwallet apply -var="network=$(NETWORK_NAME)"

tes_init:
	$(eval NETWORK_NAME=$(or $(networkName),"ethereum"))
  $(eval VAULT_TOKEN=$(or $(vaultToken),"<token_here>"))
	$(eval target_hdwallet_name=bc-wallet-$(NETWORK_NAME)-hdwallet)

	VAULT_ADDR=http://localhost:8200 \
	VAULT_TOKEN=$(VAULT_TOKEN) \
	PGUSER=postgres \
	PGDATABASE=bc-wallet-common-trrfrm \
	PGPASSWORD=password \
	PGHOST=localhost \
	PGSSLMODE=disable \
	PGPORT=5434 \
	PG_SCHEMA_NAME=bc-wallet-$(NETWORK_NAME)-hdwallet \
	terraform -chdir=deploy/trrfrm/hdwallet init -reconfigure -var="network=$(NETWORK_NAME)" \
		-var="k8s_auth_role_name=$(target_hdwallet_name)-auth-role"

trrfrm_apply:
  $(eval VAULT_TOKEN=$(or $(vaultToken),"<token_here>"))

	VAULT_ADDR=http://localhost:8200 \
	VAULT_TOKEN=$(VAULT_TOKEN) \
	PGUSER=postgres \
	PGDATABASE=bc-wallet-common-trrfrm \
	PGPASSWORD=password \
	PGHOST=localhost \
	PGSSLMODE=disable \
	PGPORT=5434 \
	PG_SCHEMA_NAME=bc-wallet-common-trrfrm \
	terraform -chdir=deploy/trrfrm/common apply

trrfrm_init:
  $(eval VAULT_TOKEN=$(or $(vaultToken),"<token_here>"))

	VAULT_ADDR=http://localhost:8200 \
	VAULT_TOKEN=$(VAULT_TOKEN) \
	PGUSER=postgres \
	PGDATABASE=bc-wallet-common-trrfrm \
	PGPASSWORD=password \
	PGHOST=localhost \
	PGSSLMODE=disable \
	PGPORT=5434 \
	PG_SCHEMA_NAME=bc-wallet-common-trrfrm \
	terraform -chdir=deploy/trrfrm/common init -reconfigure

build_trrfrm:
	$(if $(and $(env),$(repository)),,$(error 'env' and/or 'repository' is not defined))

	$(eval build_tag=$(env)-$(shell git rev-parse --short HEAD)-$(shell date +%s))
	$(eval NETWORK_CHAIN_ID=$(or $(chainID),1))
	$(eval HDWALLET_COIN_TYPE=$(or $(coinType),60))
	$(eval NETWORK_NAME=$(or $(networkName),"ethereum"))
	$(eval parent_container_path=hashicorp/terraform:latest)
	$(eval target_container_path=$(repository)/crypto-bundle/bc-wallet-common-hdwallet-trrfrmr)
	$(eval context=$(or $(context),k0s-dev-cluster))
	$(eval platform=$(or $(platform),linux/amd64))

	docker build \
		--ssh default=$(SSH_AUTH_SOCK) \
		--platform $(platform) \
		--build-arg PARENT_CONTAINER_IMAGE_NAME=$(parent_container_path) \
		--tag $(target_container_path):$(build_tag) \
		--tag $(target_container_path):latest \
		-f terraform.dockerfile .

	docker push $(target_container_path):$(build_tag)
	docker push $(target_container_path):latest