{{- /*
Copyright (c) 2022-2024 Aleksei Kotelnikov(gudron2s@gmail.com)
License: MIT NON-AI
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ pluck .Values.global.env .Values.controller.grpc_port.manager_api | first | default .Values.controller.grpc_port.manager_api._default }}
      targetPort: {{ pluck .Values.global.env .Values.controller.grpc_port.manager_api | first | default .Values.controller.grpc_port.manager_api._default }}
      protocol: TCP
      name: cntrlr-mapi

    - port: {{ pluck .Values.global.env .Values.controller.grpc_port.wallet_api | first | default .Values.controller.grpc_port.wallet_api._default }}
      targetPort: {{ pluck .Values.global.env .Values.controller.grpc_port.wallet_api | first | default .Values.controller.grpc_port.wallet_api._default }}
      protocol: TCP
      name: cntrlr-wapi

  {{ if pluck .Values.global.env .Values.controller.profiler.enabled | first | default .Values.controller.profiler.enabled._default }}
    - port: {{ pluck .Values.global.env .Values.controller.profiler.port | first | default .Values.controller.profiler.port._default }}
      targetPort: {{ pluck .Values.global.env .Values.controller.profiler.port | first | default .Values.controller.profiler.port._default }}
      protocol: TCP
      name: cntrlr-profiler
  {{ end }}
  {{ if pluck .Values.global.env .Values.api.profiler.enabled | first | default .Values.api.profiler.enabled._default }}
    - port: {{ pluck .Values.global.env .Values.api.profiler.port | first | default .Values.api.profiler.port._default }}
      targetPort: {{ pluck .Values.global.env .Values.api.profiler.port | first | default .Values.api.profiler.port._default }}
      protocol: TCP
      name: api-profiler
  {{ end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}